# Generated by Django 4.2.4 on 2023-09-01 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_name_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="amenity",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="amenity",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
