# Generated by Django 4.2.4 on 2023-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
