# Generated by Django 4.2.4 on 2023-09-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0002_experience_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="start_at",
            new_name="start",
        ),
        migrations.AlterField(
            model_name="perk",
            name="details",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
