# Generated by Django 4.2.4 on 2023-09-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("experiences", "0003_rename_start_at_experience_start_alter_perk_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
